edition                    = "2024"
error_on_line_overflow     = true
use_field_init_shorthand   = true
imports_granularity        = "Module"
condense_wildcard_suffixes = true
format_strings             = true
group_imports              = "StdExternalCrate"
chain_width                = 60
max_width                  = 180
