[formatting]
column_width        = 120
array_auto_expand   = true
allowed_blank_lines = 1
align_entries       = true

[[rule]]
keys = ["lints.clippy", "dependencies", "dev-dependencies", "build-dependencies", "toolchain", "workspace.dependencies"]

[rule.formatting]
reorder_keys = true
